### ISSUE TITLE
Delopy Fails

### ISSUE THREAD

**Issue by akhil2111** [aws-samples/aws-kube-codesuite#12]
The deploy part of the codepipeline fais.
**with all default settings fail logs:**

TART RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37 Version: $LATEST
time="2018-11-30T21:49:36Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=905624ed-97a0-4ec3-8bf8-0deae2f90f17 key=Codesuite-Demo-Pipel/BuildOutpu/iUwbWXj
time="2018-11-30T21:49:37Z" level=fatal msg="unable to get deployment file" error="BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region\n\tstatus code: 301, request id: , host id: "
2018/11/30 21:49:37 unexpected EOF
2018/11/30 21:49:37 unexpected EOF
END RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37
REPORT RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37	Duration: 950.83 ms	Billed Duration: 1000 ms Memory Size: 128 MB	Max Memory Used: 54 MB	
RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37 Process exited before completing request

START RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37 Version: $LATEST
time="2018-11-30T21:50:33Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=905624ed-97a0-4ec3-8bf8-0deae2f90f17 key=Codesuite-Demo-Pipel/BuildOutpu/iUwbWXj
time="2018-11-30T21:50:34Z" level=fatal msg="unable to get deployment file" error="BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region\n\tstatus code: 301, request id: , host id: "
2018/11/30 21:50:34 unexpected EOF
2018/11/30 21:50:34 unexpected EOF
END RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37
REPORT RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37	Duration: 923.47 ms	Billed Duration: 1000 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37 Process exited before completing request

START RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37 Version: $LATEST
time="2018-11-30T21:52:32Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=905624ed-97a0-4ec3-8bf8-0deae2f90f17 key=Codesuite-Demo-Pipel/BuildOutpu/iUwbWXj
time="2018-11-30T21:52:32Z" level=fatal msg="unable to get deployment file" error="BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region\n\tstatus code: 301, request id: , host id: "
2018/11/30 21:52:33 unexpected EOF
2018/11/30 21:52:33 unexpected EOF
END RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37
REPORT RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37	Duration: 957.76 ms	Billed Duration: 1000 ms Memory Size: 128 MB	Max Memory Used: 47 MB	
RequestId: d454e22e-f4e9-11e8-aa25-4fa624337b37 Process exited before completing request

START RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97 Version: $LATEST
time="2018-11-30T22:10:05Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=5ba32653-fd3f-47fd-a8f5-2915bd364cda key=Codesuite-Demo-Pipel/BuildOutpu/UhevLWs
time="2018-11-30T22:10:06Z" level=fatal msg="unable to get deployment file" error="BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region\n\tstatus code: 301, request id: , host id: "
2018/11/30 22:10:06 unexpected EOF
2018/11/30 22:10:06 unexpected EOF
END RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97
REPORT RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97	Duration: 965.84 ms	Billed Duration: 1000 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97 Process exited before completing request

START RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97 Version: $LATEST
time="2018-11-30T22:11:14Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=5ba32653-fd3f-47fd-a8f5-2915bd364cda key=Codesuite-Demo-Pipel/BuildOutpu/UhevLWs
time="2018-11-30T22:11:15Z" level=fatal msg="unable to get deployment file" error="BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region\n\tstatus code: 301, request id: , host id: "
2018/11/30 22:11:15 unexpected EOF
2018/11/30 22:11:15 unexpected EOF
END RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97
REPORT RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97	Duration: 1012.33 ms	Billed Duration: 1100 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97 Process exited before completing request

START RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97 Version: $LATEST
time="2018-11-30T22:13:12Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=5ba32653-fd3f-47fd-a8f5-2915bd364cda key=Codesuite-Demo-Pipel/BuildOutpu/UhevLWs
time="2018-11-30T22:13:13Z" level=fatal msg="unable to get deployment file" error="BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region\n\tstatus code: 301, request id: , host id: "
2018/11/30 22:13:13 unexpected EOF
2018/11/30 22:13:13 unexpected EOF
END RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97
REPORT RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97	Duration: 1073.99 ms	Billed Duration: 1100 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
RequestId: b147018e-f4ec-11e8-a76a-81c5906b4a97 Process exited before completing request

START RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d Version: $LATEST

**After attaching VPC and subnets attached to the lambda function Codesuite-Demo-Pipeline-8-LambdaKubernetesDeployme-1CKPUX73SZR3R fail logs:**


03:07:10
time="2018-12-01T03:07:10Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=60df1ef8-c6f6-4531-8df6-6b0f6b431952 key=Codesuite-Demo-Pipel/BuildOutpu/UhevLWs

03:08:10
END RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d

03:08:10
REPORT RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d	Duration: 60001.40 ms	Billed Duration: 60000 ms Memory Size: 128 MB	Max Memory Used: 47 MB

03:08:10
2018-12-01T03:08:10.445Z 29672097-f516-11e8-83ab-cdfe3f33828d Task timed out after 60.00 seconds

03:09:14
START RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d Version: $LATEST

03:09:14
time="2018-12-01T03:09:14Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=60df1ef8-c6f6-4531-8df6-6b0f6b431952 key=Codesuite-Demo-Pipel/BuildOutpu/UhevLWs

03:10:14
END RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d

03:10:14
REPORT RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d	Duration: 60060.33 ms	Billed Duration: 60000 ms Memory Size: 128 MB	Max Memory Used: 42 MB

03:10:14
2018-12-01T03:10:14.668Z 29672097-f516-11e8-83ab-cdfe3f33828d Task timed out after 60.06 seconds

03:12:28
START RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d Version: $LATEST

03:12:28
time="2018-12-01T03:12:28Z" level=info msg="Deployment started" bucket=codesuite-demo-pipeline-8xlviipaha-artifactbucket-ay45vyduwjb3 jobID=60df1ef8-c6f6-4531-8df6-6b0f6b431952 key=Codesuite-Demo-Pipel/BuildOutpu/UhevLWs

03:13:28
END RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d

03:13:28
REPORT RequestId: 29672097-f516-11e8-83ab-cdfe3f33828d	Duration: 60001.06 ms	Billed Duration: 60000 ms Memory Size: 128 MB	Max Memory Used: 42 MB

03:13:28
2018-12-01T03:13:28.845Z 29672097-f516-11e8-83ab-cdfe3f33828d Task timed out after 60.00 seconds

**Comment by mrichman** [comment]
I get a similar error: `AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'`

**Comment by akhil2111** [comment]
It works perfectly in Oregon try your script in this region.

**Comment by mrichman** [comment]
It should work in every region, especially us-east-1. You should not have closed this issue.

**Comment by lisaread** [comment]
+1 this is still an issue in any region besides us-west-2

**Comment by shuviru219** [comment]
@akhil2111 , did you got any solution for this . I am also getting the same error in ireland region .

**Comment by mikesigs** [comment]
Please re-open this. It is still unresolved, as there is an open PR for this issue.

**Comment by kskalvar** [comment]
Hey guys, I did find a work-around for this.  Seems that the deployment artifacts bucket needs to be in your region otherwise it fails.  Some restriction Lambda has excuting code from another region.  I did get this to work in us-east-1.  Please see https://github.com/kskalvar/aws-eks-pipeline-quickstart.  This is for EKS only!

I do have a Developer Support with AWS and have asked them to reopen the issue.  I see an Open above but not sure when or if this will ever get fixed.  Hopefully this helps.
