### ISSUE TITLE
Error when creating stack

### ISSUE THREAD

**Issue by SeriousMatt** [aws-samples/aws-kube-codesuite#8]
Getting a cloudformation error in nested stack Codesuite-Demo-SSMInject which causes the entire stack to fail:

CREATE_FAILED | The following resource(s) failed to create: [ImportCode].

The account used also has full admin permissions for AWS resources.

**Comment by SeriousMatt** [comment]
I have tracked the issue by not providing the following parameters: Client Certificate Data and Client Key Data. These parameters do not show up in my local .kube config file either.

**Comment by Netheros** [comment]
Same issue here. I think it is because by default the .kube config file uses token authentication not a client certificate.

**Comment by mohangarimella** [comment]
Were you successful? Did you get your stack working?

**Comment by SeriousMatt** [comment]
Using this script setup, no. I was new to Kubernetes at the time and
eventually I just configured the cluster manually not using this repo.
